// src/seed/seed.js
const fs = require('fs');
const path = require('path');
const { Subject, User, Post, Comment, Degree } = require('../models');


/**
 * Lee un archivo CSV y devuelve un array de objetos
 * @param {string} filePath - Ruta al archivo CSV
 * @param {Function} filterFunction - Función opcional para filtrar filas. Recibe un objeto row y debe retornar true para EXCLUIR la fila.
 * @returns {Array} - Array de objetos con los datos del CSV
 */
function readCSV(filePath, filterFunction = null) {
    const content = fs.readFileSync(filePath, 'utf-8');

    // Usar regex para separar por coma (puede tener \r antes de \n)
    const lines = content.trim().split(/\r?\n/);
    
    // Limpiar cada header: trim() + eliminar \r si quedó
    const headers = lines[0].split(';').map(h => h.trim().replace('\r', ''));
    
    const results = [];
    for (let i = 1; i < lines.length; i++) {

        // lines[i] = "1,Análisis Matemático I,1,Anual,5,Ciencias Básicas"
        // values = [1, Análisis Matemático I, "1", Anual, "5", "Ciencias Básicas"]
        const values = lines[i].split(';');
        const row = {};
        
        headers.forEach((header, index) => {
            let value = values[index]?.trim();
            
            // Convertir números si corresponde
            if (!isNaN(value) && value !== '') {
                value = Number(value);
            }
            
            row[header] = value;
        });

        // Aplicar filtro si existe
        let shouldExclude = false;
        if (filterFunction && typeof filterFunction === 'function') {
            shouldExclude = filterFunction(row);
        }
        
        if (!shouldExclude) {
            results.push(row);
        }
    }
    
    return results;
}

/**
 * Loads users from CSV file and bulk inserts them into the database.
 * 
 * This function performs the following steps:
 * 1. Reads user data from a CSV file located in the data directory
 * 2. Checks if users already exist in the database (prevents duplicate seeding)
 * 3. Transforms CSV data to match the User model schema
 * 4. Bulk inserts all users with individual hooks enabled for password hashing
 * 
 * Dependencies:
 * - CSV file must have columns: id, first_name, last_name, email, birth_date
 * - User model must have a password hashing hook (e.g., beforeCreate, beforeBulkCreate)
 * - Email field must have a unique constraint to prevent duplicates
 * 
 * @async
 * @function seedUsers
 * @returns {Promise<void>} - No return value, logs progress to console
 * 
 * @example
 * // Run first before any other seed functions that depend on users
 * await seedUsers();
 */
async function seedUsers() {
    // STEP 1: Read users from CSV file
    // Expected CSV format: id,first_name,last_name,email,birth_date
    // The 'id' column is auto-generated by the database, so it's not used in the insert
    const usersFilePath = path.join(__dirname, 'data', 'users.csv');
    const users = readCSV(usersFilePath);
    
    // STEP 2: Check if data already exists in database
    // Using findOne() is efficient since we only need to know if ANY user exists
    // This prevents duplicate seeding when the script is run multiple times
    const exists = await User.findOne();
    if (exists) {
        console.log(`✅ Users ALREADY loaded (skipping seeding)`);
        return;
    }
    
    // STEP 3: Transform CSV data to match User model schema
    // Map CSV columns to model attribute names:
    // - first_name → firstName (user's given name)
    // - last_name → lastName (user's family name/surname)
    // - email → email (unique identifier for login/contact)
    // - birth_date → birthDate (user's date of birth)
    // - password → hardcoded default value "1234" for all seeded users
    const usersData = users.map(u => ({
        firstName: u.first_name,   // Rename: CSV column 'first_name' → model field 'firstName'
        lastName: u.last_name,     // Rename: CSV column 'last_name' → model field 'lastName'
        email: u.email,            // Keep as-is, matches model field name
        birthDate: u.birth_date,   // Rename: CSV column 'birth_date' → model field 'birthDate'
        password: "1234"           // Default password for all seeded users (should be changed on first login)
    }));
    
    // STEP 4: Bulk insert all users into the database
    // Using ignoreDuplicates: true prevents errors if some emails already exist
    // (relies on the unique constraint on the email column)
    // 
    // IMPORTANT: individualHooks: true MUST be enabled!
    // Without this, Sequelize will NOT execute the beforeCreate/beforeBulkCreate hooks
    // that are responsible for hashing passwords before storing them in the database.
    // 
    // Without individualHooks: true, passwords would be stored in plain text! 
    // With individualHooks: true, each user's password is properly hashed via bcrypt
    await User.bulkCreate(usersData, {
        ignoreDuplicates: true,   // Skip records with duplicate emails (no error thrown)
        individualHooks: true     // CRITICAL: Executes beforeCreate hook for EACH record
                                  // This ensures each password is individually hashed
    });
    
    console.log(`✅ ${users.length} users successfully loaded (1 bulk insert operation)`);
}


/**
 * Loads posts from CSV file and bulk inserts them into the database.
 * 
 * This function performs the following steps:
 * 1. Reads posts data from a CSV file located in the data directory
 * 2. Checks if posts already exist in the database (prevents duplicate seeding)
 * 3. Validates that all author IDs from the CSV exist in the Users table
 * 4. Transforms CSV data to match the Post model schema
 * 5. Bulk inserts all posts into the database
 * 
 * Dependencies:
 * - This function MUST be called AFTER seedUsers() to ensure author references exist
 * - CSV file must have columns: id, title, content, author_id, subject_id, created_at
 * 
 * @async
 * @function seedPosts
 * @returns {Promise<void>} - No return value, logs progress to console
 * 
 * @example
 * // Run after seedUsers()
 * await seedPosts();
 */
async function seedPosts() {
    // STEP 1: Read posts from CSV file
    // CSV format expects: id,title,content,author_id,subject_id,created_at
    const posts = readCSV(path.join(__dirname, 'data', 'posts.csv'));
    
    // STEP 2: Check if data already exists in database
    // Count existing records - if any exist, skip seeding to avoid duplicates
    const count = await Post.count();
    if (count > 0) {
        console.log(`✅ Posts ALREADY loaded (${count} existing records)`);
        return;
    }

    // Alternative check using findOne (redundant but kept for safety)
    const exists = await Post.findOne();
    if (exists) {
        console.log(`✅ Posts ALREADY loaded`);
        return;
    }

    // STEP 3: Validate that all authors (foreign keys) exist in the Users table
    // Extract unique author IDs from the CSV data
    const authorIds = [...new Set(posts.map(p => p.author_id))];
    
    // Query database for existing users with those IDs
    const existingAuthors = await User.findAll({
        where: { id: authorIds },
        attributes: ['id']  // Only fetch the id column (efficient)
    });
    
    // Create a Set of existing IDs for O(1) lookup performance
    const existingIds = new Set(existingAuthors.map(a => a.id));
    
    // Find which author IDs from CSV are missing in the database
    const missingAuthors = authorIds.filter(id => !existingIds.has(id));
    
    // If any authors are missing, abort the seeding process
    if (missingAuthors.length > 0) {
        console.error(`❌ Missing users with IDs: ${missingAuthors.join(', ')}`);
        console.error(`   Please run seedUsers() first to create these users`);
        return;
    }
    
    console.log(`✅ All authors exist (${authorIds.length} users verified)`);
    
    // STEP 4: Transform CSV data to match Post model schema
    // Map CSV columns to model attribute names:
    // - title → title
    // - content → content
    // - author_id → authorId (foreign key to User)
    // - subject_id → subjectId (foreign key to Subject)
    // - created_at → createdAt (timestamp)
    const postsData = posts.map(p => ({
        title: p.title,
        content: p.content,
        authorId: p.author_id,      // Rename CSV column to model field
        subjectId: p.subject_id,    // Rename CSV column to model field
        createdAt: p.created_at     // Keep timestamp as-is
    }));
    
    // STEP 5: Bulk insert all posts into the database
    // Bulk insert with ignoreDuplicates: true prevents errors if some IDs already exist
    try {
        await Post.bulkCreate(postsData, { 
            ignoreDuplicates: true   // Skip duplicate IDs instead of throwing error
        });
        
        console.log(`✅ ${posts.length} posts successfully loaded (1 bulk insert operation)`);
    } catch (error) {
        // Handle any database errors (constraint violations, connection issues, etc.)
        console.error('❌ Failed to create posts:', error.message);
        console.error('Error details:', error.original);
    }
}


/**
 * Loads comments from CSV file and bulk inserts them into the database.
 * Includes validation for both author and post foreign keys.
 * 
 * @async
 * @function seedComments
 * @returns {Promise<void>}
 */
async function seedComments() {
    // STEP 1: Read comments from CSV file
    const commentsFilePath = path.join(__dirname, 'data', 'comments.csv');
    const comments = readCSV(commentsFilePath);
    
    // STEP 2: Check if data already exists
    const exists = await Comment.findOne();
    if (exists) {
        console.log(`✅ Comments ALREADY loaded (skipping seeding)`);
        return;
    }
    
    // STEP 3: Validate that all authors (foreign key to Users) exist
    const authorIds = [...new Set(comments.map(c => c.author_id))];
    const existingAuthors = await User.findAll({
        where: { id: authorIds },
        attributes: ['id']
    });
    
    const existingAuthorIds = new Set(existingAuthors.map(a => a.id));
    const missingAuthors = authorIds.filter(id => !existingAuthorIds.has(id));
    
    if (missingAuthors.length > 0) {
        console.error(`❌ Missing users (authors) with IDs: ${missingAuthors.join(', ')}`);
        console.error(`   Please run seedUsers() first`);
        return;
    }
    
    // STEP 4: Validate that all posts (foreign key to Posts) exist
    const postIds = [...new Set(comments.map(c => c.post_id))];
    const existingPosts = await Post.findAll({
        where: { id: postIds },
        attributes: ['id']
    });
    
    const existingPostIds = new Set(existingPosts.map(p => p.id));
    const missingPosts = postIds.filter(id => !existingPostIds.has(id));
    
    if (missingPosts.length > 0) {
        console.error(`❌ Missing posts with IDs: ${missingPosts.join(', ')}`);
        console.error(`   Please run seedPosts() first`);
        return;
    }
    
    console.log(`✅ All authors (${authorIds.length}) and posts (${postIds.length}) exist`);
    
    // STEP 5: Transform CSV data to match Comment model schema
    const commentsData = comments.map(c => ({
        content: c.content,
        authorId: c.author_id,
        postId: c.post_id,
        createdAt: c.created_at
    }));
    
    // STEP 6: Bulk insert all comments
    await Comment.bulkCreate(commentsData, { 
        ignoreDuplicates: true 
    });
    
    console.log(`✅ ${comments.length} comments successfully loaded (1 bulk insert operation)`);
}


/**
 * Carga materias desde CSV usando bulkCreate para minimizar hits a la DB
 */
async function seedSubjects() {
    
    // Verificar si ya hay materias cargadas
    const exists = await Subject.findOne();
    if (exists) {
        console.log(`✅ Materias YA cargadas previamente. Se omite la carga.`);
        return;
    }

    // Verificar si el archivo existe
    const csvPath = path.join(__dirname, 'data', 'subjects.csv');
    if (!fs.existsSync(csvPath)) {
        console.log(`❌ Archivo no encontrado: ${csvPath}`);
        return;
    }

    /* 
        subject = {
            id: 1,
            nombre: "algo",
            nivel: 2,
            carrera: "Ciencias Básicas" ó "Ingeniería en Sistemas"
        }
    */  

    /**
     * Filter function that includes each unique Ciencias Básicas subject only once.
     * Since the same subject may appear multiple times across different engineering
     * programs (e.g., Física I appears in Sistemas, Industrial, Mecánica, etc.),
     * this filter ensures we only load each unique subject name once.
     * 
     * @param {Object} subject - The subject row from CSV
     * @param {Object} seenSubjects - Cache object to track already included subjects
     * @returns {boolean} - Returns true to EXCLUDE the subject, false to INCLUDE it
     */
    const createUniqueBasicSubjectsFilter = () => {
        const seenSubjects = {};
        
        return (subject) => {
            // EXCLUDE: Non-basic sciences subjects
            if (subject.carrera !== 'Ciencias Básicas') {
                return true;  // Skip this subject (exclude)
            }
            
            // If this subject name hasn't been seen yet
            if (!seenSubjects[subject.nombre]) {
                seenSubjects[subject.nombre] = true;  // Mark as seen
                return false;  // INCLUDE this subject (first occurrence only)
            }
            
            // This is a duplicate of an already included Ciencias Básicas subject
            return true;  // EXCLUDE duplicate
        };
    };

    // Leer CSV con filtro opcional
    const subjects = readCSV(csvPath, customFilter);
    
    if (subjects.length === 0) {
        console.log(`⚠️ No se encontraron materias para cargar (posiblemente todas fueron filtradas)`);
        return;
    }
    
    
    // 1. Extraer todas las carreras únicas del CSV
    const uniqueCareers = [...new Set(subjects.map(s => s.carrera))];
    
    // 2. Obtener o crear Degrees (solo 1 hit por carrera única)
    const degreeMap = new Map();
    for (const careerName of uniqueCareers) {
        const [degree] = await Degree.findOrCreate({
            where: { name: careerName },
            defaults: { name: careerName }
        });
        degreeMap.set(careerName, degree.id);
        
        /*
        degreeMap = {
            "Ciencias Básicas": 1,
            "Ingeniería en Sistemas": 2
        }
        */
    }
    
    // 3. Preparar datos de Subjects para bulkCreate
    const subjectsData = subjects.map(subject => ({
        name: subject.nombre,
        year: subject.nivel,
        isElective: ['si', 'sí', '1', 'yes', 'true'].includes(subject.es_electiva?.toLowerCase()),
        degreeId: degreeMap.get(subject.carrera)
    }));
    
    // 4. Bulk insert - UN SOLO hit a la DB
    await Subject.bulkCreate(subjectsData, {
        ignoreDuplicates: true  // Evita errores si ya existen
    });
    
    console.log(`✅ ${subjects.length} materias cargadas (${degreeMap.size} degrees, 1 bulk insert)`);
}


/**
 * Master seed orchestrator that executes all seeding functions in the correct order.
 * 
 * This function coordinates the sequential execution of all individual seed functions,
 * ensuring that foreign key dependencies are respected. It acts as the main entry point
 * for populating the database with initial/test data.
 * 
 * Execution order is CRITICAL due to foreign key constraints:
 * 1. Users must be created first (referenced by Posts and Comments)
 * 2. Subjects must be created second (referenced by Posts)
 * 3. Posts must be created third (depends on Users and Subjects)
 * 4. Comments must be created last (depends on Users and Posts)
 * 
 * @async
 * @function runSeed
 * @returns {Promise<void>} - No return value, logs progress to console
 * 
 * @example
 * // Run from command line or script
 * runSeed().then(() => console.log('Done'));
 * 
 * @example
 * // With error handling
 * try {
 *     await runSeed();
 * } catch (error) {
 *     console.error('Seeding failed:', error);
 * }
 */
async function runSeed() {
    try {
        console.log('🌱 Starting database seeding process...');
        console.log('Following dependency chain: Users → Subjects → Posts → Comments\n');
        
        // STEP 1: Create users FIRST
        // Users are the foundation - no foreign keys depend on other tables
        // Posts and Comments both reference Users (authorId)
        console.log('┌─────────────────────────────────────────┐');
        console.log('│ STEP 1/4: Seeding Users (base layer)    │');
        console.log('└─────────────────────────────────────────┘');
        await seedUsers();
        console.log(''); // Empty line for readability
        
        // STEP 2: Create subjects SECOND
        // Subjects are independent but referenced by Posts
        // No dependencies on other tables
        console.log('┌─────────────────────────────────────────┐');
        console.log('│ STEP 2/4: Seeding Subjects              │');
        console.log('└─────────────────────────────────────────┘');
        await seedSubjects();
        console.log(''); // Empty line for readability
        
        // STEP 3: Create posts THIRD
        // Posts depend on Users (authorId) and Subjects (subjectId)
        // Both dependencies must exist before this step
        console.log('┌─────────────────────────────────────────┐');
        console.log('│ STEP 3/4: Seeding Posts                 │');
        console.log('│ (depends on Users + Subjects)           │');
        console.log('└─────────────────────────────────────────┘');
        await seedPosts();
        console.log(''); // Empty line for readability
        
        // STEP 4: Create comments LAST
        // Comments depend on Users (authorId) and Posts (postId)
        // All dependencies must exist before this step
        console.log('┌─────────────────────────────────────────┐');
        console.log('│ STEP 4/4: Seeding Comments              │');
        console.log('│ (depends on Users + Posts)              │');
        console.log('└─────────────────────────────────────────┘');
        await seedComments();
        
        // All seeding completed successfully
        console.log('\n========================================');
        console.log('✅ SEEDING COMPLETED SUCCESSFULLY');
        console.log('========================================');
        
        // Optional: Uncomment to exit the process with success code
        // process.exit(0);
        
    } catch (error) {
        // Handle any errors that occurred during the seeding process
        console.error('\n========================================');
        console.error('❌ SEEDING FAILED');
        console.error('========================================');
        console.error('Error details:', error.message);
        console.error('Full error:', error);
        
        // Optional: Uncomment to exit the process with error code
        // process.exit(1);
    }
}


module.exports = { readCSV, runSeed };